version: '3.8'

services:
  claude-code-ui:
    image: claude-code-ui:latest
    container_name: claude-code-ui
    ports:
      - "${PORT:-3008}:${PORT:-3008}"
    environment:
      # Server Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3008}

      # Anthropic API Configuration
      - ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL:-https://api.anthropic.com}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

      # Claude CLI Configuration
      - CLAUDE_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-sonnet}

      # Security Configuration
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-24h}

      # Project Configuration
      - DEFAULT_PROJECT_PATH=${DEFAULT_PROJECT_PATH:-/workspace}
      - AUTO_CREATE_PROJECTS=${AUTO_CREATE_PROJECTS:-true}

      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}

    volumes:
      # Persistent data storage
      - claude_data:/app/data
      # Claude CLI configuration and sessions
      - claude_sessions:/home/claudeui/.claude
      # Project workspace (customize as needed)
      - ${WORKSPACE_PATH:-./workspace}:/workspace
      # Optional: Mount your projects directory
      - ${PROJECTS_PATH:-~/Documents}:/home/claudeui/Documents

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3008/api/config', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: claude-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - claude-code-ui
    restart: unless-stopped
    networks:
      - claude-network
    profiles:
      - production

volumes:
  claude_data:
    driver: local
  claude_sessions:
    driver: local

networks:
  claude-network:
    driver: bridge
