version: '3.8'

services:
  claude-code:
    image: claude-code-ui:latest
    container_name: claude-code-ui
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - PORT=3008
    volumes:
      # Mount data directory for persistence
      - claude_data:/app/data
      # Mount Claude CLI directory (if available on host)
      - ~/.claude:/home/claudeui/.claude:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3008/api/config', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: claude-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - claude-code-ui
    restart: unless-stopped
    networks:
      - claude-network
    profiles:
      - production

volumes:
  claude_data:
    driver: local

networks:
  claude-network:
    driver: bridge
